version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Updated to Node 20 for React Router compatibility
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - mkdir -p src/assets/images
      - echo Creating placeholder images if missing...
      - touch src/assets/images/aceternity.webp
      - touch src/assets/images/cotype_Foundry_Favicon.webp
      - touch src/assets/images/FluxAcademy.webp


  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Checking build output...
      - ls -la dist/  # Verify build output
      # - echo Syncing to S3...
      # - aws s3 sync dist/ s3://anokye-codecompass --delete  # Changed from build/ to dist/
      # - echo Deployment completed successfully

artifacts:
  files:
    - '**/*'
  base-directory: dist  # Changed from build to dist (Vite uses dist/)
  discard-paths: no
